// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// recom
void recom(Rcpp::String input_file, Rcpp::String output_file, Rcpp::LogicalVector remove_space);
RcppExport SEXP _recom_recom(SEXP input_fileSEXP, SEXP output_fileSEXP, SEXP remove_spaceSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type output_file(output_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type remove_space(remove_spaceSEXP);
    recom(input_file, output_file, remove_space);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_recom_recom", (DL_FUNC) &_recom_recom, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_recom(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
