# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' recom refers to REmove COMments of Rscript file
#' @param input_file input source Rscript file
#' @param output_file output Rscript file
#' @param remove_space is an optional boolean flag to remove free space of comments
NULL

recom <- function(input_file, output_file, remove_space = TRUE) {
    invisible(.Call(`_recom_recom`, input_file, output_file, remove_space))
}

